/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class BaseLocationSpacelessSet implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public BaseLocationSpacelessSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BaseLocationSpacelessSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_BaseLocationSpacelessSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BaseLocationSpacelessSet(SWIGTYPE_p_std__setT_BaseLocation_p_t original) {
    this(bridgeJNI.new_BaseLocationSpacelessSet(SWIGTYPE_p_std__setT_BaseLocation_p_t.getCPtr(original)), true);
  }

  public int size() {
    return bridgeJNI.BaseLocationSpacelessSet_size(swigCPtr, this);
  }

  public boolean contains(SWIGTYPE_p_BaseLocation item) {
    return bridgeJNI.BaseLocationSpacelessSet_contains(swigCPtr, this, SWIGTYPE_p_BaseLocation.getCPtr(item));
  }

  public boolean add(SWIGTYPE_p_BaseLocation item) {
    return bridgeJNI.BaseLocationSpacelessSet_add(swigCPtr, this, SWIGTYPE_p_BaseLocation.getCPtr(item));
  }

  public void clear() {
    bridgeJNI.BaseLocationSpacelessSet_clear(swigCPtr, this);
  }

  public boolean remove(SWIGTYPE_p_BaseLocation item) {
    return bridgeJNI.BaseLocationSpacelessSet_remove(swigCPtr, this, SWIGTYPE_p_BaseLocation.getCPtr(item));
  }

}
