/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;

public interface bridgeConstants {
  // CoordinateType 
  public final static int Screen = 1;
  public final static int Map = 2;
  public final static int Mouse = 3;

  // Flag 
  public final static int CompleteMapInformation = 0;
  public final static int UserInput = 1;

  // Latency 
  public final static int SinglePlayer = 2;
  public final static int LanLow = 5;
  public final static int LanMedium = 7;
  public final static int LanHigh = 9;
  public final static int BattlenetLow = 14;
  public final static int BattlenetMedium = 19;
  public final static int BattlenetHigh = 24;

}
