/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class ChokepointGetSidesPair implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ChokepointGetSidesPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ChokepointGetSidesPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_ChokepointGetSidesPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ChokepointGetSidesPair() {
    this(bridgeJNI.new_ChokepointGetSidesPair__SWIG_0(), true);
  }

  public ChokepointGetSidesPair(SWIG_Position first, SWIG_Position second) {
    this(bridgeJNI.new_ChokepointGetSidesPair__SWIG_1(SWIG_Position.getCPtr(first), first, SWIG_Position.getCPtr(second), second), true);
  }

  public ChokepointGetSidesPair(ChokepointGetSidesPair p) {
    this(bridgeJNI.new_ChokepointGetSidesPair__SWIG_2(ChokepointGetSidesPair.getCPtr(p), p), true);
  }

  public void setFirst(SWIG_Position value) {
    bridgeJNI.ChokepointGetSidesPair_first_set(swigCPtr, this, SWIG_Position.getCPtr(value), value);
  }

  public SWIG_Position getFirst() {
    long cPtr = bridgeJNI.ChokepointGetSidesPair_first_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIG_Position(cPtr, false);
  }

  public void setSecond(SWIG_Position value) {
    bridgeJNI.ChokepointGetSidesPair_second_set(swigCPtr, this, SWIG_Position.getCPtr(value), value);
  }

  public SWIG_Position getSecond() {
    long cPtr = bridgeJNI.ChokepointGetSidesPair_second_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIG_Position(cPtr, false);
  }

}
