/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class ChokepointGetRegionsPair implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ChokepointGetRegionsPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ChokepointGetRegionsPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_ChokepointGetRegionsPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ChokepointGetRegionsPair() {
    this(bridgeJNI.new_ChokepointGetRegionsPair__SWIG_0(), true);
  }

  public ChokepointGetRegionsPair(SWIG_Region first, SWIG_Region second) {
    this(bridgeJNI.new_ChokepointGetRegionsPair__SWIG_1(SWIG_Region.getCPtr(first), first, SWIG_Region.getCPtr(second), second), true);
  }

  public ChokepointGetRegionsPair(ChokepointGetRegionsPair p) {
    this(bridgeJNI.new_ChokepointGetRegionsPair__SWIG_2(ChokepointGetRegionsPair.getCPtr(p), p), true);
  }

  public void setFirst(SWIG_Region value) {
    bridgeJNI.ChokepointGetRegionsPair_first_set(swigCPtr, this, SWIG_Region.getCPtr(value), value);
  }

  public SWIG_Region getFirst() {
    long cPtr = bridgeJNI.ChokepointGetRegionsPair_first_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIG_Region(cPtr, false);
  }

  public void setSecond(SWIG_Region value) {
    bridgeJNI.ChokepointGetRegionsPair_second_set(swigCPtr, this, SWIG_Region.getCPtr(value), value);
  }

  public SWIG_Region getSecond() {
    long cPtr = bridgeJNI.ChokepointGetRegionsPair_second_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIG_Region(cPtr, false);
  }

}
