/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class ExplosionTypeSet implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ExplosionTypeSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ExplosionTypeSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_ExplosionTypeSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ExplosionTypeSet(SWIGTYPE_p_std__setT_BWAPI__ExplosionType_t original) {
    this(bridgeJNI.new_ExplosionTypeSet(SWIGTYPE_p_std__setT_BWAPI__ExplosionType_t.getCPtr(original)), true);
  }

  public int size() {
    return bridgeJNI.ExplosionTypeSet_size(swigCPtr, this);
  }

  public boolean contains(SWIG_ExplosionType item) {
    return bridgeJNI.ExplosionTypeSet_contains(swigCPtr, this, SWIG_ExplosionType.getCPtr(item), item);
  }

  public boolean add(SWIG_ExplosionType item) {
    return bridgeJNI.ExplosionTypeSet_add(swigCPtr, this, SWIG_ExplosionType.getCPtr(item), item);
  }

  public void clear() {
    bridgeJNI.ExplosionTypeSet_clear(swigCPtr, this);
  }

  public boolean remove(SWIG_ExplosionType item) {
    return bridgeJNI.ExplosionTypeSet_remove(swigCPtr, this, SWIG_ExplosionType.getCPtr(item), item);
  }

}
