/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class ForceSetIterator implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ForceSetIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ForceSetIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_ForceSetIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ForceSetIterator(SWIGTYPE_p_std__setT_BWAPI__Force_p_t original) {
    this(bridgeJNI.new_ForceSetIterator(SWIGTYPE_p_std__setT_BWAPI__Force_p_t.getCPtr(original)), true);
  }

  public boolean hasNext() {
    return bridgeJNI.ForceSetIterator_hasNext(swigCPtr, this);
  }

  public SWIG_Force next() {
    long cPtr = bridgeJNI.ForceSetIterator_next(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIG_Force(cPtr, false);
  }

}
