/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class OrderSet implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public OrderSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OrderSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_OrderSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OrderSet(SWIGTYPE_p_std__setT_BWAPI__Order_t original) {
    this(bridgeJNI.new_OrderSet(SWIGTYPE_p_std__setT_BWAPI__Order_t.getCPtr(original)), true);
  }

  public int size() {
    return bridgeJNI.OrderSet_size(swigCPtr, this);
  }

  public boolean contains(SWIG_Order item) {
    return bridgeJNI.OrderSet_contains(swigCPtr, this, SWIG_Order.getCPtr(item), item);
  }

  public boolean add(SWIG_Order item) {
    return bridgeJNI.OrderSet_add(swigCPtr, this, SWIG_Order.getCPtr(item), item);
  }

  public void clear() {
    bridgeJNI.OrderSet_clear(swigCPtr, this);
  }

  public boolean remove(SWIG_Order item) {
    return bridgeJNI.OrderSet_remove(swigCPtr, this, SWIG_Order.getCPtr(item), item);
  }

}
