/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class OrderSetIterator implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public OrderSetIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OrderSetIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_OrderSetIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OrderSetIterator(SWIGTYPE_p_std__setT_BWAPI__Order_t original) {
    this(bridgeJNI.new_OrderSetIterator(SWIGTYPE_p_std__setT_BWAPI__Order_t.getCPtr(original)), true);
  }

  public boolean hasNext() {
    return bridgeJNI.OrderSetIterator_hasNext(swigCPtr, this);
  }

  public SWIG_Order next() {
    return new SWIG_Order(bridgeJNI.OrderSetIterator_next(swigCPtr, this), true);
  }

}
