/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class PlayerSet implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public PlayerSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(PlayerSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_PlayerSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PlayerSet(SWIGTYPE_p_std__setT_BWAPI__Player_p_t original) {
    this(bridgeJNI.new_PlayerSet(SWIGTYPE_p_std__setT_BWAPI__Player_p_t.getCPtr(original)), true);
  }

  public int size() {
    return bridgeJNI.PlayerSet_size(swigCPtr, this);
  }

  public boolean contains(SWIG_Player item) {
    return bridgeJNI.PlayerSet_contains(swigCPtr, this, SWIG_Player.getCPtr(item), item);
  }

  public boolean add(SWIG_Player item) {
    return bridgeJNI.PlayerSet_add(swigCPtr, this, SWIG_Player.getCPtr(item), item);
  }

  public void clear() {
    bridgeJNI.PlayerSet_clear(swigCPtr, this);
  }

  public boolean remove(SWIG_Player item) {
    return bridgeJNI.PlayerSet_remove(swigCPtr, this, SWIG_Player.getCPtr(item), item);
  }

}
