/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class PolygonSet implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public PolygonSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(PolygonSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_PolygonSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PolygonSet(SWIGTYPE_p_std__setT_BWTA__Polygon_p_t original) {
    this(bridgeJNI.new_PolygonSet(SWIGTYPE_p_std__setT_BWTA__Polygon_p_t.getCPtr(original)), true);
  }

  public int size() {
    return bridgeJNI.PolygonSet_size(swigCPtr, this);
  }

  public boolean contains(SWIG_Polygon item) {
    return bridgeJNI.PolygonSet_contains(swigCPtr, this, SWIG_Polygon.getCPtr(item), item);
  }

  public boolean add(SWIG_Polygon item) {
    return bridgeJNI.PolygonSet_add(swigCPtr, this, SWIG_Polygon.getCPtr(item), item);
  }

  public void clear() {
    bridgeJNI.PolygonSet_clear(swigCPtr, this);
  }

  public boolean remove(SWIG_Polygon item) {
    return bridgeJNI.PolygonSet_remove(swigCPtr, this, SWIG_Polygon.getCPtr(item), item);
  }

}
