/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class PositionVector implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public PositionVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(PositionVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_PositionVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PositionVector(SWIGTYPE_p_std__vectorT_BWAPI__Position_t original) {
    this(bridgeJNI.new_PositionVector(SWIGTYPE_p_std__vectorT_BWAPI__Position_t.getCPtr(original)), true);
  }

  public int size() {
    return bridgeJNI.PositionVector_size(swigCPtr, this);
  }

  public void add(int index, SWIG_Position item) {
    bridgeJNI.PositionVector_add(swigCPtr, this, index, SWIG_Position.getCPtr(item), item);
  }

  public void clear() {
    bridgeJNI.PositionVector_clear(swigCPtr, this);
  }

  public SWIG_Position set(int index, SWIG_Position item) {
    return new SWIG_Position(bridgeJNI.PositionVector_set(swigCPtr, this, index, SWIG_Position.getCPtr(item), item), true);
  }

  public SWIG_Position remove(int index) {
    return new SWIG_Position(bridgeJNI.PositionVector_remove(swigCPtr, this, index), true);
  }

  public SWIG_Position get(int index) {
    return new SWIG_Position(bridgeJNI.PositionVector_get(swigCPtr, this, index), true);
  }

}
