/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class RaceSet implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public RaceSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(RaceSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_RaceSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RaceSet(SWIGTYPE_p_std__setT_BWAPI__Race_t original) {
    this(bridgeJNI.new_RaceSet(SWIGTYPE_p_std__setT_BWAPI__Race_t.getCPtr(original)), true);
  }

  public int size() {
    return bridgeJNI.RaceSet_size(swigCPtr, this);
  }

  public boolean contains(SWIG_Race item) {
    return bridgeJNI.RaceSet_contains(swigCPtr, this, SWIG_Race.getCPtr(item), item);
  }

  public boolean add(SWIG_Race item) {
    return bridgeJNI.RaceSet_add(swigCPtr, this, SWIG_Race.getCPtr(item), item);
  }

  public void clear() {
    bridgeJNI.RaceSet_clear(swigCPtr, this);
  }

  public boolean remove(SWIG_Race item) {
    return bridgeJNI.RaceSet_remove(swigCPtr, this, SWIG_Race.getCPtr(item), item);
  }

}
