/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class RegionSet implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public RegionSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(RegionSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_RegionSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RegionSet(SWIGTYPE_p_std__setT_BWTA__Region_p_t original) {
    this(bridgeJNI.new_RegionSet(SWIGTYPE_p_std__setT_BWTA__Region_p_t.getCPtr(original)), true);
  }

  public int size() {
    return bridgeJNI.RegionSet_size(swigCPtr, this);
  }

  public boolean contains(SWIG_Region item) {
    return bridgeJNI.RegionSet_contains(swigCPtr, this, SWIG_Region.getCPtr(item), item);
  }

  public boolean add(SWIG_Region item) {
    return bridgeJNI.RegionSet_add(swigCPtr, this, SWIG_Region.getCPtr(item), item);
  }

  public void clear() {
    bridgeJNI.RegionSet_clear(swigCPtr, this);
  }

  public boolean remove(SWIG_Region item) {
    return bridgeJNI.RegionSet_remove(swigCPtr, this, SWIG_Region.getCPtr(item), item);
  }

}
