/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class SWIG_PlayerType implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public SWIG_PlayerType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SWIG_PlayerType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_SWIG_PlayerType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIG_PlayerType() {
    this(bridgeJNI.new_SWIG_PlayerType__SWIG_0(), true);
  }

  public SWIG_PlayerType(int id) {
    this(bridgeJNI.new_SWIG_PlayerType__SWIG_1(id), true);
  }

  public SWIG_PlayerType(SWIG_PlayerType other) {
    this(bridgeJNI.new_SWIG_PlayerType__SWIG_2(SWIG_PlayerType.getCPtr(other), other), true);
  }

  public SWIG_PlayerType opAssign(SWIG_PlayerType other) {
    return new SWIG_PlayerType(bridgeJNI.SWIG_PlayerType_opAssign(swigCPtr, this, SWIG_PlayerType.getCPtr(other), other), false);
  }

  public boolean opEquals(SWIG_PlayerType other) {
    return bridgeJNI.SWIG_PlayerType_opEquals(swigCPtr, this, SWIG_PlayerType.getCPtr(other), other);
  }

  public boolean opNotEquals(SWIG_PlayerType other) {
    return bridgeJNI.SWIG_PlayerType_opNotEquals(swigCPtr, this, SWIG_PlayerType.getCPtr(other), other);
  }

  public boolean opLessThan(SWIG_PlayerType other) {
    return bridgeJNI.SWIG_PlayerType_opLessThan(swigCPtr, this, SWIG_PlayerType.getCPtr(other), other);
  }

  public int getID() {
    return bridgeJNI.SWIG_PlayerType_getID(swigCPtr, this);
  }

  public String getName() {
    return bridgeJNI.SWIG_PlayerType_getName(swigCPtr, this);
  }

}
