/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class SWIG_DamageType implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public SWIG_DamageType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SWIG_DamageType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_SWIG_DamageType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIG_DamageType() {
    this(bridgeJNI.new_SWIG_DamageType__SWIG_0(), true);
  }

  public SWIG_DamageType(int id) {
    this(bridgeJNI.new_SWIG_DamageType__SWIG_1(id), true);
  }

  public SWIG_DamageType(SWIG_DamageType other) {
    this(bridgeJNI.new_SWIG_DamageType__SWIG_2(SWIG_DamageType.getCPtr(other), other), true);
  }

  public SWIG_DamageType opAssign(SWIG_DamageType other) {
    return new SWIG_DamageType(bridgeJNI.SWIG_DamageType_opAssign(swigCPtr, this, SWIG_DamageType.getCPtr(other), other), false);
  }

  public boolean opEquals(SWIG_DamageType other) {
    return bridgeJNI.SWIG_DamageType_opEquals(swigCPtr, this, SWIG_DamageType.getCPtr(other), other);
  }

  public boolean opNotEquals(SWIG_DamageType other) {
    return bridgeJNI.SWIG_DamageType_opNotEquals(swigCPtr, this, SWIG_DamageType.getCPtr(other), other);
  }

  public boolean opLessThan(SWIG_DamageType other) {
    return bridgeJNI.SWIG_DamageType_opLessThan(swigCPtr, this, SWIG_DamageType.getCPtr(other), other);
  }

  public int getID() {
    return bridgeJNI.SWIG_DamageType_getID(swigCPtr, this);
  }

  public String getName() {
    return bridgeJNI.SWIG_DamageType_getName(swigCPtr, this);
  }

}
