/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class SWIG_Player implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public SWIG_Player(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SWIG_Player obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_SWIG_Player(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getID() {
    return bridgeJNI.SWIG_Player_getID(swigCPtr, this);
  }

  public String getName() {
    return bridgeJNI.SWIG_Player_getName(swigCPtr, this);
  }

  public SWIGTYPE_p_std__setT_BWAPI__Unit_p_t getUnits() {
    return new SWIGTYPE_p_std__setT_BWAPI__Unit_p_t(bridgeJNI.SWIG_Player_getUnits(swigCPtr, this), false);
  }

  public SWIGTYPE_p_Race getRace() {
    return new SWIGTYPE_p_Race(bridgeJNI.SWIG_Player_getRace(swigCPtr, this), true);
  }

  public SWIGTYPE_p_PlayerType playerType() {
    return new SWIGTYPE_p_PlayerType(bridgeJNI.SWIG_Player_playerType(swigCPtr, this), true);
  }

  public SWIG_Force getForce() {
    long cPtr = bridgeJNI.SWIG_Player_getForce(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIG_Force(cPtr, false);
  }

  public boolean isAlly(SWIG_Player player) {
    return bridgeJNI.SWIG_Player_isAlly(swigCPtr, this, SWIG_Player.getCPtr(player), player);
  }

  public boolean isEnemy(SWIG_Player player) {
    return bridgeJNI.SWIG_Player_isEnemy(swigCPtr, this, SWIG_Player.getCPtr(player), player);
  }

  public boolean isNeutral() {
    return bridgeJNI.SWIG_Player_isNeutral(swigCPtr, this);
  }

  public SWIGTYPE_p_TilePosition getStartLocation() {
    return new SWIGTYPE_p_TilePosition(bridgeJNI.SWIG_Player_getStartLocation(swigCPtr, this), true);
  }

  public boolean leftGame() {
    return bridgeJNI.SWIG_Player_leftGame(swigCPtr, this);
  }

  public int minerals() {
    return bridgeJNI.SWIG_Player_minerals(swigCPtr, this);
  }

  public int gas() {
    return bridgeJNI.SWIG_Player_gas(swigCPtr, this);
  }

  public int cumulativeMinerals() {
    return bridgeJNI.SWIG_Player_cumulativeMinerals(swigCPtr, this);
  }

  public int cumulativeGas() {
    return bridgeJNI.SWIG_Player_cumulativeGas(swigCPtr, this);
  }

  public int supplyTotal() {
    return bridgeJNI.SWIG_Player_supplyTotal__SWIG_0(swigCPtr, this);
  }

  public int supplyUsed() {
    return bridgeJNI.SWIG_Player_supplyUsed__SWIG_0(swigCPtr, this);
  }

  public int supplyTotal(SWIGTYPE_p_Race race) {
    return bridgeJNI.SWIG_Player_supplyTotal__SWIG_1(swigCPtr, this, SWIGTYPE_p_Race.getCPtr(race));
  }

  public int supplyUsed(SWIGTYPE_p_Race race) {
    return bridgeJNI.SWIG_Player_supplyUsed__SWIG_1(swigCPtr, this, SWIGTYPE_p_Race.getCPtr(race));
  }

  public int allUnitCount(SWIG_UnitType unit) {
    return bridgeJNI.SWIG_Player_allUnitCount(swigCPtr, this, SWIG_UnitType.getCPtr(unit), unit);
  }

  public int completedUnitCount(SWIG_UnitType unit) {
    return bridgeJNI.SWIG_Player_completedUnitCount(swigCPtr, this, SWIG_UnitType.getCPtr(unit), unit);
  }

  public int incompleteUnitCount(SWIG_UnitType unit) {
    return bridgeJNI.SWIG_Player_incompleteUnitCount(swigCPtr, this, SWIG_UnitType.getCPtr(unit), unit);
  }

  public int deadUnitCount(SWIG_UnitType unit) {
    return bridgeJNI.SWIG_Player_deadUnitCount(swigCPtr, this, SWIG_UnitType.getCPtr(unit), unit);
  }

  public int killedUnitCount(SWIG_UnitType unit) {
    return bridgeJNI.SWIG_Player_killedUnitCount(swigCPtr, this, SWIG_UnitType.getCPtr(unit), unit);
  }

  public int getUpgradeLevel(SWIGTYPE_p_UpgradeType upgrade) {
    return bridgeJNI.SWIG_Player_getUpgradeLevel(swigCPtr, this, SWIGTYPE_p_UpgradeType.getCPtr(upgrade));
  }

  public boolean hasResearched(SWIGTYPE_p_TechType tech) {
    return bridgeJNI.SWIG_Player_hasResearched(swigCPtr, this, SWIGTYPE_p_TechType.getCPtr(tech));
  }

  public boolean isResearching(SWIGTYPE_p_TechType tech) {
    return bridgeJNI.SWIG_Player_isResearching(swigCPtr, this, SWIGTYPE_p_TechType.getCPtr(tech));
  }

  public boolean isUpgrading(SWIGTYPE_p_UpgradeType upgrade) {
    return bridgeJNI.SWIG_Player_isUpgrading(swigCPtr, this, SWIGTYPE_p_UpgradeType.getCPtr(upgrade));
  }

}
