/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class SWIG_ExplosionType implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public SWIG_ExplosionType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SWIG_ExplosionType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_SWIG_ExplosionType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIG_ExplosionType() {
    this(bridgeJNI.new_SWIG_ExplosionType__SWIG_0(), true);
  }

  public SWIG_ExplosionType(int id) {
    this(bridgeJNI.new_SWIG_ExplosionType__SWIG_1(id), true);
  }

  public SWIG_ExplosionType(SWIG_ExplosionType other) {
    this(bridgeJNI.new_SWIG_ExplosionType__SWIG_2(SWIG_ExplosionType.getCPtr(other), other), true);
  }

  public SWIG_ExplosionType opAssign(SWIG_ExplosionType other) {
    return new SWIG_ExplosionType(bridgeJNI.SWIG_ExplosionType_opAssign(swigCPtr, this, SWIG_ExplosionType.getCPtr(other), other), false);
  }

  public boolean opEquals(SWIG_ExplosionType other) {
    return bridgeJNI.SWIG_ExplosionType_opEquals(swigCPtr, this, SWIG_ExplosionType.getCPtr(other), other);
  }

  public boolean opNotEquals(SWIG_ExplosionType other) {
    return bridgeJNI.SWIG_ExplosionType_opNotEquals(swigCPtr, this, SWIG_ExplosionType.getCPtr(other), other);
  }

  public boolean opLessThan(SWIG_ExplosionType other) {
    return bridgeJNI.SWIG_ExplosionType_opLessThan(swigCPtr, this, SWIG_ExplosionType.getCPtr(other), other);
  }

  public int getID() {
    return bridgeJNI.SWIG_ExplosionType_getID(swigCPtr, this);
  }

  public String getName() {
    return bridgeJNI.SWIG_ExplosionType_getName(swigCPtr, this);
  }

}
