/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class SWIG_BaseLocation implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public SWIG_BaseLocation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SWIG_BaseLocation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_SWIG_BaseLocation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIG_Position getPosition() {
    return new SWIG_Position(bridgeJNI.SWIG_BaseLocation_getPosition(swigCPtr, this), true);
  }

  public SWIG_TilePosition getTilePosition() {
    return new SWIG_TilePosition(bridgeJNI.SWIG_BaseLocation_getTilePosition(swigCPtr, this), true);
  }

  public SWIG_Region getRegion() {
    long cPtr = bridgeJNI.SWIG_BaseLocation_getRegion(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIG_Region(cPtr, false);
  }

  public int minerals() {
    return bridgeJNI.SWIG_BaseLocation_minerals(swigCPtr, this);
  }

  public int gas() {
    return bridgeJNI.SWIG_BaseLocation_gas(swigCPtr, this);
  }

  public SWIGTYPE_p_std__setT_BWAPI__Unit_p_t getMinerals() {
    return new SWIGTYPE_p_std__setT_BWAPI__Unit_p_t(bridgeJNI.SWIG_BaseLocation_getMinerals(swigCPtr, this), false);
  }

  public SWIGTYPE_p_std__setT_BWAPI__Unit_p_t getStaticMinerals() {
    return new SWIGTYPE_p_std__setT_BWAPI__Unit_p_t(bridgeJNI.SWIG_BaseLocation_getStaticMinerals(swigCPtr, this), false);
  }

  public SWIGTYPE_p_std__setT_BWAPI__Unit_p_t getGeysers() {
    return new SWIGTYPE_p_std__setT_BWAPI__Unit_p_t(bridgeJNI.SWIG_BaseLocation_getGeysers(swigCPtr, this), false);
  }

  public double getGroundDistance(SWIG_BaseLocation other) {
    return bridgeJNI.SWIG_BaseLocation_getGroundDistance(swigCPtr, this, SWIG_BaseLocation.getCPtr(other), other);
  }

  public double getAirDistance(SWIG_BaseLocation other) {
    return bridgeJNI.SWIG_BaseLocation_getAirDistance(swigCPtr, this, SWIG_BaseLocation.getCPtr(other), other);
  }

  public boolean isIsland() {
    return bridgeJNI.SWIG_BaseLocation_isIsland(swigCPtr, this);
  }

  public boolean isMineralOnly() {
    return bridgeJNI.SWIG_BaseLocation_isMineralOnly(swigCPtr, this);
  }

  public boolean isStartLocation() {
    return bridgeJNI.SWIG_BaseLocation_isStartLocation(swigCPtr, this);
  }

}
