/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class SWIG_Race implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public SWIG_Race(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SWIG_Race obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_SWIG_Race(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIG_Race() {
    this(bridgeJNI.new_SWIG_Race__SWIG_0(), true);
  }

  public SWIG_Race(int id) {
    this(bridgeJNI.new_SWIG_Race__SWIG_1(id), true);
  }

  public SWIG_Race(SWIG_Race other) {
    this(bridgeJNI.new_SWIG_Race__SWIG_2(SWIG_Race.getCPtr(other), other), true);
  }

  public SWIG_Race opAssign(SWIG_Race other) {
    return new SWIG_Race(bridgeJNI.SWIG_Race_opAssign(swigCPtr, this, SWIG_Race.getCPtr(other), other), false);
  }

  public boolean opEquals(SWIG_Race other) {
    return bridgeJNI.SWIG_Race_opEquals(swigCPtr, this, SWIG_Race.getCPtr(other), other);
  }

  public boolean opNotEquals(SWIG_Race other) {
    return bridgeJNI.SWIG_Race_opNotEquals(swigCPtr, this, SWIG_Race.getCPtr(other), other);
  }

  public boolean opLessThan(SWIG_Race other) {
    return bridgeJNI.SWIG_Race_opLessThan(swigCPtr, this, SWIG_Race.getCPtr(other), other);
  }

  public int getID() {
    return bridgeJNI.SWIG_Race_getID(swigCPtr, this);
  }

  public String getName() {
    return bridgeJNI.SWIG_Race_getName(swigCPtr, this);
  }

  public SWIG_UnitType getWorker() {
    long cPtr = bridgeJNI.SWIG_Race_getWorker(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIG_UnitType(cPtr, false);
  }

  public SWIG_UnitType getCenter() {
    long cPtr = bridgeJNI.SWIG_Race_getCenter(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIG_UnitType(cPtr, false);
  }

  public SWIG_UnitType getRefinery() {
    long cPtr = bridgeJNI.SWIG_Race_getRefinery(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIG_UnitType(cPtr, false);
  }

  public SWIG_UnitType getTransport() {
    long cPtr = bridgeJNI.SWIG_Race_getTransport(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIG_UnitType(cPtr, false);
  }

  public SWIG_UnitType getSupplyProvider() {
    long cPtr = bridgeJNI.SWIG_Race_getSupplyProvider(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIG_UnitType(cPtr, false);
  }

}
