/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class SWIG_Error implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public SWIG_Error(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SWIG_Error obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_SWIG_Error(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIG_Error() {
    this(bridgeJNI.new_SWIG_Error__SWIG_0(), true);
  }

  public SWIG_Error(int id) {
    this(bridgeJNI.new_SWIG_Error__SWIG_1(id), true);
  }

  public SWIG_Error(SWIG_Error other) {
    this(bridgeJNI.new_SWIG_Error__SWIG_2(SWIG_Error.getCPtr(other), other), true);
  }

  public SWIG_Error opAssign(SWIG_Error other) {
    return new SWIG_Error(bridgeJNI.SWIG_Error_opAssign(swigCPtr, this, SWIG_Error.getCPtr(other), other), false);
  }

  public boolean opEquals(SWIG_Error other) {
    return bridgeJNI.SWIG_Error_opEquals(swigCPtr, this, SWIG_Error.getCPtr(other), other);
  }

  public boolean opNotEquals(SWIG_Error other) {
    return bridgeJNI.SWIG_Error_opNotEquals(swigCPtr, this, SWIG_Error.getCPtr(other), other);
  }

  public boolean opLessThan(SWIG_Error other) {
    return bridgeJNI.SWIG_Error_opLessThan(swigCPtr, this, SWIG_Error.getCPtr(other), other);
  }

  public int getID() {
    return bridgeJNI.SWIG_Error_getID(swigCPtr, this);
  }

  public String toErrorString() {
    return bridgeJNI.SWIG_Error_toErrorString(swigCPtr, this);
  }

}
