/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class SWIG_UpgradeType implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public SWIG_UpgradeType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SWIG_UpgradeType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_SWIG_UpgradeType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIG_UpgradeType() {
    this(bridgeJNI.new_SWIG_UpgradeType__SWIG_0(), true);
  }

  public SWIG_UpgradeType(int id) {
    this(bridgeJNI.new_SWIG_UpgradeType__SWIG_1(id), true);
  }

  public SWIG_UpgradeType(SWIG_UpgradeType other) {
    this(bridgeJNI.new_SWIG_UpgradeType__SWIG_2(SWIG_UpgradeType.getCPtr(other), other), true);
  }

  public SWIG_UpgradeType opAssign(SWIG_UpgradeType other) {
    return new SWIG_UpgradeType(bridgeJNI.SWIG_UpgradeType_opAssign(swigCPtr, this, SWIG_UpgradeType.getCPtr(other), other), false);
  }

  public boolean opEquals(SWIG_UpgradeType other) {
    return bridgeJNI.SWIG_UpgradeType_opEquals(swigCPtr, this, SWIG_UpgradeType.getCPtr(other), other);
  }

  public boolean opNotEquals(SWIG_UpgradeType other) {
    return bridgeJNI.SWIG_UpgradeType_opNotEquals(swigCPtr, this, SWIG_UpgradeType.getCPtr(other), other);
  }

  public boolean opLessThan(SWIG_UpgradeType other) {
    return bridgeJNI.SWIG_UpgradeType_opLessThan(swigCPtr, this, SWIG_UpgradeType.getCPtr(other), other);
  }

  public int getID() {
    return bridgeJNI.SWIG_UpgradeType_getID(swigCPtr, this);
  }

  public String getName() {
    return bridgeJNI.SWIG_UpgradeType_getName(swigCPtr, this);
  }

  public SWIG_Race getRace() {
    return new SWIG_Race(bridgeJNI.SWIG_UpgradeType_getRace(swigCPtr, this), true);
  }

  public int mineralPriceBase() {
    return bridgeJNI.SWIG_UpgradeType_mineralPriceBase(swigCPtr, this);
  }

  public int mineralPriceFactor() {
    return bridgeJNI.SWIG_UpgradeType_mineralPriceFactor(swigCPtr, this);
  }

  public int gasPriceBase() {
    return bridgeJNI.SWIG_UpgradeType_gasPriceBase(swigCPtr, this);
  }

  public int gasPriceFactor() {
    return bridgeJNI.SWIG_UpgradeType_gasPriceFactor(swigCPtr, this);
  }

  public int upgradeTimeBase() {
    return bridgeJNI.SWIG_UpgradeType_upgradeTimeBase(swigCPtr, this);
  }

  public int upgradeTimeFactor() {
    return bridgeJNI.SWIG_UpgradeType_upgradeTimeFactor(swigCPtr, this);
  }

  public int maxRepeats() {
    return bridgeJNI.SWIG_UpgradeType_maxRepeats(swigCPtr, this);
  }

  public SWIG_UnitType whatUpgrades() {
    long cPtr = bridgeJNI.SWIG_UpgradeType_whatUpgrades(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIG_UnitType(cPtr, false);
  }

  public SWIGTYPE_p_std__setT_BWAPI__UnitType_const_p_t whatUses() {
    return new SWIGTYPE_p_std__setT_BWAPI__UnitType_const_p_t(bridgeJNI.SWIG_UpgradeType_whatUses(swigCPtr, this), false);
  }

}
