/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class SWIG_Polygon implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public SWIG_Polygon(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SWIG_Polygon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_SWIG_Polygon(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIG_Polygon() {
    this(bridgeJNI.new_SWIG_Polygon(), true);
  }

  public double getArea() {
    return bridgeJNI.SWIG_Polygon_getArea(swigCPtr, this);
  }

  public double getPerimeter() {
    return bridgeJNI.SWIG_Polygon_getPerimeter(swigCPtr, this);
  }

  public SWIG_Position getCenter() {
    return new SWIG_Position(bridgeJNI.SWIG_Polygon_getCenter(swigCPtr, this), true);
  }

  public boolean isInside(SWIG_Position p) {
    return bridgeJNI.SWIG_Polygon_isInside(swigCPtr, this, SWIG_Position.getCPtr(p), p);
  }

  public SWIG_Position getNearestPoint(SWIG_Position p) {
    return new SWIG_Position(bridgeJNI.SWIG_Polygon_getNearestPoint(swigCPtr, this, SWIG_Position.getCPtr(p), p), true);
  }

}
