/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class SWIG_TechType implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public SWIG_TechType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SWIG_TechType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_SWIG_TechType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIG_TechType() {
    this(bridgeJNI.new_SWIG_TechType__SWIG_0(), true);
  }

  public SWIG_TechType(int id) {
    this(bridgeJNI.new_SWIG_TechType__SWIG_1(id), true);
  }

  public SWIG_TechType(SWIG_TechType other) {
    this(bridgeJNI.new_SWIG_TechType__SWIG_2(SWIG_TechType.getCPtr(other), other), true);
  }

  public SWIG_TechType opAssign(SWIG_TechType other) {
    return new SWIG_TechType(bridgeJNI.SWIG_TechType_opAssign(swigCPtr, this, SWIG_TechType.getCPtr(other), other), false);
  }

  public boolean opEquals(SWIG_TechType other) {
    return bridgeJNI.SWIG_TechType_opEquals(swigCPtr, this, SWIG_TechType.getCPtr(other), other);
  }

  public boolean opNotEquals(SWIG_TechType other) {
    return bridgeJNI.SWIG_TechType_opNotEquals(swigCPtr, this, SWIG_TechType.getCPtr(other), other);
  }

  public boolean opLessThan(SWIG_TechType other) {
    return bridgeJNI.SWIG_TechType_opLessThan(swigCPtr, this, SWIG_TechType.getCPtr(other), other);
  }

  public int getID() {
    return bridgeJNI.SWIG_TechType_getID(swigCPtr, this);
  }

  public String getName() {
    return bridgeJNI.SWIG_TechType_getName(swigCPtr, this);
  }

  public int mineralPrice() {
    return bridgeJNI.SWIG_TechType_mineralPrice(swigCPtr, this);
  }

  public int gasPrice() {
    return bridgeJNI.SWIG_TechType_gasPrice(swigCPtr, this);
  }

  public int energyUsed() {
    return bridgeJNI.SWIG_TechType_energyUsed(swigCPtr, this);
  }

  public SWIG_UnitType whatResearches() {
    long cPtr = bridgeJNI.SWIG_TechType_whatResearches(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIG_UnitType(cPtr, false);
  }

  public SWIG_WeaponType getWeapon() {
    long cPtr = bridgeJNI.SWIG_TechType_getWeapon(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIG_WeaponType(cPtr, false);
  }

  public SWIGTYPE_p_std__setT_BWAPI__UnitType_const_p_t whatUses() {
    return new SWIGTYPE_p_std__setT_BWAPI__UnitType_const_p_t(bridgeJNI.SWIG_TechType_whatUses(swigCPtr, this), false);
  }

}
