/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class SWIG_UnitSizeType implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public SWIG_UnitSizeType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SWIG_UnitSizeType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_SWIG_UnitSizeType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIG_UnitSizeType() {
    this(bridgeJNI.new_SWIG_UnitSizeType__SWIG_0(), true);
  }

  public SWIG_UnitSizeType(int id) {
    this(bridgeJNI.new_SWIG_UnitSizeType__SWIG_1(id), true);
  }

  public SWIG_UnitSizeType(SWIG_UnitSizeType other) {
    this(bridgeJNI.new_SWIG_UnitSizeType__SWIG_2(SWIG_UnitSizeType.getCPtr(other), other), true);
  }

  public SWIG_UnitSizeType opAssign(SWIG_UnitSizeType other) {
    return new SWIG_UnitSizeType(bridgeJNI.SWIG_UnitSizeType_opAssign(swigCPtr, this, SWIG_UnitSizeType.getCPtr(other), other), false);
  }

  public boolean opEquals(SWIG_UnitSizeType other) {
    return bridgeJNI.SWIG_UnitSizeType_opEquals(swigCPtr, this, SWIG_UnitSizeType.getCPtr(other), other);
  }

  public boolean opNotEquals(SWIG_UnitSizeType other) {
    return bridgeJNI.SWIG_UnitSizeType_opNotEquals(swigCPtr, this, SWIG_UnitSizeType.getCPtr(other), other);
  }

  public boolean opLessThan(SWIG_UnitSizeType other) {
    return bridgeJNI.SWIG_UnitSizeType_opLessThan(swigCPtr, this, SWIG_UnitSizeType.getCPtr(other), other);
  }

  public int getID() {
    return bridgeJNI.SWIG_UnitSizeType_getID(swigCPtr, this);
  }

  public String getName() {
    return bridgeJNI.SWIG_UnitSizeType_getName(swigCPtr, this);
  }

}
