/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class SWIG_Color implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public SWIG_Color(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SWIG_Color obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_SWIG_Color(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIG_Color() {
    this(bridgeJNI.new_SWIG_Color__SWIG_0(), true);
  }

  public SWIG_Color(int id) {
    this(bridgeJNI.new_SWIG_Color__SWIG_1(id), true);
  }

  public SWIG_Color(SWIG_Color other) {
    this(bridgeJNI.new_SWIG_Color__SWIG_2(SWIG_Color.getCPtr(other), other), true);
  }

  public SWIG_Color(int red, int green, int blue) {
    this(bridgeJNI.new_SWIG_Color__SWIG_3(red, green, blue), true);
  }

  public SWIG_Color opAssign(SWIG_Color other) {
    return new SWIG_Color(bridgeJNI.SWIG_Color_opAssign(swigCPtr, this, SWIG_Color.getCPtr(other), other), false);
  }

  public boolean opEquals(SWIG_Color other) {
    return bridgeJNI.SWIG_Color_opEquals(swigCPtr, this, SWIG_Color.getCPtr(other), other);
  }

  public boolean opNotEquals(SWIG_Color other) {
    return bridgeJNI.SWIG_Color_opNotEquals(swigCPtr, this, SWIG_Color.getCPtr(other), other);
  }

  public boolean opLessThan(SWIG_Color other) {
    return bridgeJNI.SWIG_Color_opLessThan(swigCPtr, this, SWIG_Color.getCPtr(other), other);
  }

  public int getID() {
    return bridgeJNI.SWIG_Color_getID(swigCPtr, this);
  }

  public int red() {
    return bridgeJNI.SWIG_Color_red(swigCPtr, this);
  }

  public int green() {
    return bridgeJNI.SWIG_Color_green(swigCPtr, this);
  }

  public int blue() {
    return bridgeJNI.SWIG_Color_blue(swigCPtr, this);
  }

}
