/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class SWIGTYPE_p_std__setT_BWAPI__TilePosition_t implements BwapiPointable {
  private long swigCPtr;

  public SWIGTYPE_p_std__setT_BWAPI__TilePosition_t(long cPtr, boolean bFutureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_std__setT_BWAPI__TilePosition_t() {
    swigCPtr = 0;
  }

  public static long getCPtr(SWIGTYPE_p_std__setT_BWAPI__TilePosition_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
  
  public long getCPtr() {
    return swigCPtr;
  }
}

