/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class SWIG_AttackType implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public SWIG_AttackType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SWIG_AttackType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_SWIG_AttackType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIG_AttackType() {
    this(bridgeJNI.new_SWIG_AttackType__SWIG_0(), true);
  }

  public SWIG_AttackType(int id) {
    this(bridgeJNI.new_SWIG_AttackType__SWIG_1(id), true);
  }

  public SWIG_AttackType(SWIG_AttackType other) {
    this(bridgeJNI.new_SWIG_AttackType__SWIG_2(SWIG_AttackType.getCPtr(other), other), true);
  }

  public SWIG_AttackType opAssign(SWIG_AttackType other) {
    return new SWIG_AttackType(bridgeJNI.SWIG_AttackType_opAssign(swigCPtr, this, SWIG_AttackType.getCPtr(other), other), false);
  }

  public boolean opEquals(SWIG_AttackType other) {
    return bridgeJNI.SWIG_AttackType_opEquals(swigCPtr, this, SWIG_AttackType.getCPtr(other), other);
  }

  public boolean opNotEquals(SWIG_AttackType other) {
    return bridgeJNI.SWIG_AttackType_opNotEquals(swigCPtr, this, SWIG_AttackType.getCPtr(other), other);
  }

  public boolean opLessThan(SWIG_AttackType other) {
    return bridgeJNI.SWIG_AttackType_opLessThan(swigCPtr, this, SWIG_AttackType.getCPtr(other), other);
  }

  public int getID() {
    return bridgeJNI.SWIG_AttackType_getID(swigCPtr, this);
  }

  public String getName() {
    return bridgeJNI.SWIG_AttackType_getName(swigCPtr, this);
  }

}
