/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class TechTypeSet implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public TechTypeSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(TechTypeSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_TechTypeSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TechTypeSet(SWIGTYPE_p_std__setT_BWAPI__TechType_t original) {
    this(bridgeJNI.new_TechTypeSet(SWIGTYPE_p_std__setT_BWAPI__TechType_t.getCPtr(original)), true);
  }

  public int size() {
    return bridgeJNI.TechTypeSet_size(swigCPtr, this);
  }

  public boolean contains(SWIG_TechType item) {
    return bridgeJNI.TechTypeSet_contains(swigCPtr, this, SWIG_TechType.getCPtr(item), item);
  }

  public boolean add(SWIG_TechType item) {
    return bridgeJNI.TechTypeSet_add(swigCPtr, this, SWIG_TechType.getCPtr(item), item);
  }

  public void clear() {
    bridgeJNI.TechTypeSet_clear(swigCPtr, this);
  }

  public boolean remove(SWIG_TechType item) {
    return bridgeJNI.TechTypeSet_remove(swigCPtr, this, SWIG_TechType.getCPtr(item), item);
  }

}
