/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class TechTypeConstantSet implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public TechTypeConstantSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(TechTypeConstantSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_TechTypeConstantSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TechTypeConstantSet(SWIGTYPE_p_std__setT_BWAPI__TechType_const_p_t original) {
    this(bridgeJNI.new_TechTypeConstantSet(SWIGTYPE_p_std__setT_BWAPI__TechType_const_p_t.getCPtr(original)), true);
  }

  public int size() {
    return bridgeJNI.TechTypeConstantSet_size(swigCPtr, this);
  }

  public boolean contains(SWIG_TechType item) {
    return bridgeJNI.TechTypeConstantSet_contains(swigCPtr, this, SWIG_TechType.getCPtr(item), item);
  }

  public boolean add(SWIG_TechType item) {
    return bridgeJNI.TechTypeConstantSet_add(swigCPtr, this, SWIG_TechType.getCPtr(item), item);
  }

  public void clear() {
    bridgeJNI.TechTypeConstantSet_clear(swigCPtr, this);
  }

  public boolean remove(SWIG_TechType item) {
    return bridgeJNI.TechTypeConstantSet_remove(swigCPtr, this, SWIG_TechType.getCPtr(item), item);
  }

}
