/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class TilePositionSet implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public TilePositionSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(TilePositionSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_TilePositionSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TilePositionSet(SWIGTYPE_p_std__setT_BWAPI__TilePosition_t original) {
    this(bridgeJNI.new_TilePositionSet(SWIGTYPE_p_std__setT_BWAPI__TilePosition_t.getCPtr(original)), true);
  }

  public int size() {
    return bridgeJNI.TilePositionSet_size(swigCPtr, this);
  }

  public boolean contains(SWIG_TilePosition item) {
    return bridgeJNI.TilePositionSet_contains(swigCPtr, this, SWIG_TilePosition.getCPtr(item), item);
  }

  public boolean add(SWIG_TilePosition item) {
    return bridgeJNI.TilePositionSet_add(swigCPtr, this, SWIG_TilePosition.getCPtr(item), item);
  }

  public void clear() {
    bridgeJNI.TilePositionSet_clear(swigCPtr, this);
  }

  public boolean remove(SWIG_TilePosition item) {
    return bridgeJNI.TilePositionSet_remove(swigCPtr, this, SWIG_TilePosition.getCPtr(item), item);
  }

}
