/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class UnitSet implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public UnitSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(UnitSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_UnitSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UnitSet(SWIGTYPE_p_std__setT_BWAPI__Unit_p_t original) {
    this(bridgeJNI.new_UnitSet(SWIGTYPE_p_std__setT_BWAPI__Unit_p_t.getCPtr(original)), true);
  }

  public int size() {
    return bridgeJNI.UnitSet_size(swigCPtr, this);
  }

  public boolean contains(SWIG_Unit item) {
    return bridgeJNI.UnitSet_contains(swigCPtr, this, SWIG_Unit.getCPtr(item), item);
  }

  public boolean add(SWIG_Unit item) {
    return bridgeJNI.UnitSet_add(swigCPtr, this, SWIG_Unit.getCPtr(item), item);
  }

  public void clear() {
    bridgeJNI.UnitSet_clear(swigCPtr, this);
  }

  public boolean remove(SWIG_Unit item) {
    return bridgeJNI.UnitSet_remove(swigCPtr, this, SWIG_Unit.getCPtr(item), item);
  }

}
