/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class UnitTypeSet implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public UnitTypeSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(UnitTypeSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_UnitTypeSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UnitTypeSet(SWIGTYPE_p_std__setT_BWAPI__UnitType_t original) {
    this(bridgeJNI.new_UnitTypeSet(SWIGTYPE_p_std__setT_BWAPI__UnitType_t.getCPtr(original)), true);
  }

  public int size() {
    return bridgeJNI.UnitTypeSet_size(swigCPtr, this);
  }

  public boolean contains(SWIG_UnitType item) {
    return bridgeJNI.UnitTypeSet_contains(swigCPtr, this, SWIG_UnitType.getCPtr(item), item);
  }

  public boolean add(SWIG_UnitType item) {
    return bridgeJNI.UnitTypeSet_add(swigCPtr, this, SWIG_UnitType.getCPtr(item), item);
  }

  public void clear() {
    bridgeJNI.UnitTypeSet_clear(swigCPtr, this);
  }

  public boolean remove(SWIG_UnitType item) {
    return bridgeJNI.UnitTypeSet_remove(swigCPtr, this, SWIG_UnitType.getCPtr(item), item);
  }

}
