/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class UnitTypeListIterator implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public UnitTypeListIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(UnitTypeListIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_UnitTypeListIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UnitTypeListIterator(SWIGTYPE_p_std__listT_BWAPI__UnitType_t original) {
    this(bridgeJNI.new_UnitTypeListIterator(SWIGTYPE_p_std__listT_BWAPI__UnitType_t.getCPtr(original)), true);
  }

  public boolean hasNext() {
    return bridgeJNI.UnitTypeListIterator_hasNext(swigCPtr, this);
  }

  public SWIG_UnitType next() {
    return new SWIG_UnitType(bridgeJNI.UnitTypeListIterator_next(swigCPtr, this), true);
  }

}
