/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class UnitSizeTypeSet implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public UnitSizeTypeSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(UnitSizeTypeSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_UnitSizeTypeSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UnitSizeTypeSet(SWIGTYPE_p_std__setT_BWAPI__UnitSizeType_t original) {
    this(bridgeJNI.new_UnitSizeTypeSet(SWIGTYPE_p_std__setT_BWAPI__UnitSizeType_t.getCPtr(original)), true);
  }

  public int size() {
    return bridgeJNI.UnitSizeTypeSet_size(swigCPtr, this);
  }

  public boolean contains(SWIG_UnitSizeType item) {
    return bridgeJNI.UnitSizeTypeSet_contains(swigCPtr, this, SWIG_UnitSizeType.getCPtr(item), item);
  }

  public boolean add(SWIG_UnitSizeType item) {
    return bridgeJNI.UnitSizeTypeSet_add(swigCPtr, this, SWIG_UnitSizeType.getCPtr(item), item);
  }

  public void clear() {
    bridgeJNI.UnitSizeTypeSet_clear(swigCPtr, this);
  }

  public boolean remove(SWIG_UnitSizeType item) {
    return bridgeJNI.UnitSizeTypeSet_remove(swigCPtr, this, SWIG_UnitSizeType.getCPtr(item), item);
  }

}
