/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class UnitTypeWhatBuildsPair implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public UnitTypeWhatBuildsPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(UnitTypeWhatBuildsPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_UnitTypeWhatBuildsPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UnitTypeWhatBuildsPair() {
    this(bridgeJNI.new_UnitTypeWhatBuildsPair__SWIG_0(), true);
  }

  public UnitTypeWhatBuildsPair(SWIG_UnitType first, int second) {
    this(bridgeJNI.new_UnitTypeWhatBuildsPair__SWIG_1(SWIG_UnitType.getCPtr(first), first, second), true);
  }

  public UnitTypeWhatBuildsPair(UnitTypeWhatBuildsPair p) {
    this(bridgeJNI.new_UnitTypeWhatBuildsPair__SWIG_2(UnitTypeWhatBuildsPair.getCPtr(p), p), true);
  }

  public void setFirst(SWIG_UnitType value) {
    bridgeJNI.UnitTypeWhatBuildsPair_first_set(swigCPtr, this, SWIG_UnitType.getCPtr(value), value);
  }

  public SWIG_UnitType getFirst() {
    long cPtr = bridgeJNI.UnitTypeWhatBuildsPair_first_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIG_UnitType(cPtr, false);
  }

  public void setSecond(int value) {
    bridgeJNI.UnitTypeWhatBuildsPair_second_set(swigCPtr, this, value);
  }

  public int getSecond() {
    return bridgeJNI.UnitTypeWhatBuildsPair_second_get(swigCPtr, this);
  }

}
