/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class UnitList implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public UnitList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(UnitList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_UnitList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_list(SWIGTYPE_p_std__listT_BWAPI__Unit_p_t value) {
    bridgeJNI.UnitList__list_set(swigCPtr, this, SWIGTYPE_p_std__listT_BWAPI__Unit_p_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__listT_BWAPI__Unit_p_t get_list() {
    long cPtr = bridgeJNI.UnitList__list_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__listT_BWAPI__Unit_p_t(cPtr, false);
  }

  public UnitList(SWIGTYPE_p_std__listT_BWAPI__Unit_p_t original) {
    this(bridgeJNI.new_UnitList(SWIGTYPE_p_std__listT_BWAPI__Unit_p_t.getCPtr(original)), true);
  }

  public int size() {
    return bridgeJNI.UnitList_size(swigCPtr, this);
  }

  public boolean contains(SWIG_Unit item) {
    return bridgeJNI.UnitList_contains(swigCPtr, this, SWIG_Unit.getCPtr(item), item);
  }

  public boolean add(SWIG_Unit item) {
    return bridgeJNI.UnitList_add(swigCPtr, this, SWIG_Unit.getCPtr(item), item);
  }

  public void clear() {
    bridgeJNI.UnitList_clear(swigCPtr, this);
  }

  public boolean remove(SWIG_Unit item) {
    return bridgeJNI.UnitList_remove(swigCPtr, this, SWIG_Unit.getCPtr(item), item);
  }

}
