/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class UnitTypeMapIterator implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public UnitTypeMapIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(UnitTypeMapIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_UnitTypeMapIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UnitTypeMapIterator(SWIGTYPE_p_std__mapT_UnitType_const_p_int_t original) {
    this(bridgeJNI.new_UnitTypeMapIterator(SWIGTYPE_p_std__mapT_UnitType_const_p_int_t.getCPtr(original)), true);
  }

  public boolean hasNext() {
    return bridgeJNI.UnitTypeMapIterator_hasNext(swigCPtr, this);
  }

  public void next() {
    bridgeJNI.UnitTypeMapIterator_next(swigCPtr, this);
  }

  public SWIGTYPE_p_UnitType getKey() {
    long cPtr = bridgeJNI.UnitTypeMapIterator_getKey(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_UnitType(cPtr, false);
  }

  public int getValue() {
    return bridgeJNI.UnitTypeMapIterator_getValue(swigCPtr, this);
  }

}
