/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bwapi.bridge.swig;
import org.bwapi.bridge.model.BwapiPointable;
public class WeaponTypeSet implements BwapiPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public WeaponTypeSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(WeaponTypeSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public long getCPtr() {
    return swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bridgeJNI.delete_WeaponTypeSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public WeaponTypeSet(SWIGTYPE_p_std__setT_BWAPI__WeaponType_t original) {
    this(bridgeJNI.new_WeaponTypeSet(SWIGTYPE_p_std__setT_BWAPI__WeaponType_t.getCPtr(original)), true);
  }

  public int size() {
    return bridgeJNI.WeaponTypeSet_size(swigCPtr, this);
  }

  public boolean contains(SWIG_WeaponType item) {
    return bridgeJNI.WeaponTypeSet_contains(swigCPtr, this, SWIG_WeaponType.getCPtr(item), item);
  }

  public boolean add(SWIG_WeaponType item) {
    return bridgeJNI.WeaponTypeSet_add(swigCPtr, this, SWIG_WeaponType.getCPtr(item), item);
  }

  public void clear() {
    bridgeJNI.WeaponTypeSet_clear(swigCPtr, this);
  }

  public boolean remove(SWIG_WeaponType item) {
    return bridgeJNI.WeaponTypeSet_remove(swigCPtr, this, SWIG_WeaponType.getCPtr(item), item);
  }

}
